-- Active: 1775724267059@@127.0.0.1@3306@christian_bio_data
-- Generated by the database client.
CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT,
    role VARCHAR(20),
    email VARCHAR(100),
    password_hash TEXT,
    father VARCHAR(100),
    mother VARCHAR(100),
    tribe VARCHAR(50),
    clan VARCHAR(50),
    birth_place VARCHAR(100),
    birth_date DATE,
    subcounty VARCHAR(100),
    residence VARCHAR(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    parish_id INT,
    verified BOOLEAN DEFAULT FALSE,
    phone_number VARCHAR(20),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    middle_name VARCHAR(100),
    registration_number VARCHAR(50),
    PRIMARY KEY(id),
    UNIQUE KEY users_email_key (email),
    UNIQUE KEY registration_number_unique (registration_number)
) ENGINE=InnoDB;


-- Generated by the database client.
CREATE TABLE parishes(
    parish_id INT NOT NULL AUTO_INCREMENT,
    parish_name VARCHAR(100) NOT NULL,
    deanery VARCHAR(100) NOT NULL,
    PRIMARY KEY(parish_id)
) ENGINE=InnoDB;


-- Generated by the database client.
CREATE TABLE baptism(
    baptism_id INT NOT NULL AUTO_INCREMENT,
    user_id INT,
    parish VARCHAR(100),
    baptism_date DATE,
    minister VARCHAR(100),
    sponsor VARCHAR(100),
    baptism_number VARCHAR(50),
    PRIMARY KEY(baptism_id),
    UNIQUE KEY baptism_baptism_number_key (baptism_number),
    CONSTRAINT baptism_user_id_fkey FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;


-- Generated by the database client.
CREATE TABLE confirmation(
    confirmation_id INT NOT NULL AUTO_INCREMENT,
    user_id INT,
    confirmation_place VARCHAR(100),
    confirmation_date DATE,
    confirmation_no VARCHAR(50),
    minister VARCHAR(100),
    PRIMARY KEY(confirmation_id),
    CONSTRAINT confirmation_user_id_fkey FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;


-- Generated by the database client.
CREATE TABLE eucharist(
    eucharist_id INT NOT NULL AUTO_INCREMENT,
    user_id INT,
    eucharist_place VARCHAR(100),
    eucharist_date DATE,
    PRIMARY KEY(eucharist_id),
    CONSTRAINT eucharist_user_id_fkey FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;


-- Generated by the database client.
CREATE TABLE marriages(
    marriage_id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    certificate_number VARCHAR(50),
    submission_location VARCHAR(100),
    submission_sub_county VARCHAR(100),
    submission_county VARCHAR(100),
    marriage_date DATE,
    marriage_entry_number VARCHAR(50),
    special_license_number VARCHAR(50),
    conducted_by VARCHAR(100),
    private_parties_count INT,
    private_parties_names TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    registrar_certification_number VARCHAR(50),
    PRIMARY KEY(marriage_id),
    UNIQUE KEY marriages_certificate_number_key (certificate_number),
    CONSTRAINT marriages_user_id_fkey FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;


-- Generated by the database client.
CREATE TABLE marriage_parties(
    party_id INT NOT NULL AUTO_INCREMENT,
    marriage_id INT NOT NULL,
    party_type VARCHAR(20),
    full_name VARCHAR(100),
    age INT,
    marital_status VARCHAR(50),
    residence_address TEXT,
    residence_county VARCHAR(100),
    residence_sub_county VARCHAR(100),
    occupation VARCHAR(100),
    father_name VARCHAR(100),
    father_occupation VARCHAR(100),
    father_residence TEXT,
    mother_name VARCHAR(100),
    mother_occupation VARCHAR(100),
    mother_residence TEXT,
    PRIMARY KEY(party_id),
    CONSTRAINT marriage_parties_marriage_id_fkey FOREIGN KEY(marriage_id) REFERENCES marriages(marriage_id) ON DELETE CASCADE,
    CONSTRAINT marriage_parties_party_type_check CHECK (party_type IN ('bride', 'groom'))
) ENGINE=InnoDB;


-- Generated by the database client.
CREATE TABLE marriage_documents(
    document_id INT NOT NULL AUTO_INCREMENT,
    marriage_id INT NOT NULL,
    document_type VARCHAR(50),
    file_name VARCHAR(255),
    file_path TEXT,
    file_size BIGINT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(document_id),
    CONSTRAINT marriage_documents_marriage_id_fkey FOREIGN KEY(marriage_id) REFERENCES marriages(marriage_id) ON DELETE CASCADE
) ENGINE=InnoDB;


INSERT INTO parishes (parish_name, deanery) VALUES
('Cathedral Parish', 'Nyeri Municipality Deanery'),
('St. Jude Parish', 'Nyeri Municipality Deanery'),
('King\'ong\'o Parish', 'Nyeri Municipality Deanery'),
('Mwenji Parish', 'Nyeri Municipality Deanery'),
('Kiamuiru Parish', 'Nyeri Municipality Deanery'),
('Mathari Institutions Chaplaincy', 'Nyeri Municipality Deanery'),
('St. Charles Lwanga Parish', 'Nyeri Municipality Deanery'),
('Mukurwe-ini Parish', 'Mukurwe-ini Deanery'),
('Kaheti Parish', 'Mukurwe-ini Deanery'),
('Kimondo Parish', 'Mukurwe-ini Deanery'),
('Gikondi Parish', 'Mukurwe-ini Deanery'),
('Othaya Parish', 'Othaya Deanery'),
('Kariko Parish', 'Othaya Deanery'),
('Birithia Parish', 'Othaya Deanery'),
('Karima Parish', 'Othaya Deanery'),
('Kagicha Parish', 'Othaya Deanery'),
('Karuthi Parish', 'Othaya Deanery'),
('Kigumo Parish', 'Othaya Deanery'),
('Nanyuki Parish', 'Nanyuki Deanery'),
('Dol Dol Parish', 'Nanyuki Deanery'),
('Matanya Parish', 'Nanyuki Deanery'),
('St. Teresa Parish', 'Nanyuki Deanery'),
('Kalalu Parish', 'Nanyuki Deanery'),
('Narumoru Town Parish', 'Narumoru Deanery'),
('Irigithathi Parish', 'Narumoru Deanery'),
('Thegu Parish', 'Narumoru Deanery'),
('Arch-angel Michael Chaka Parish', 'Narumoru Deanery'),
('Munyu Parish', 'Narumoru Deanery'),
('Karatina Parish', 'Karatina Deanery'),
('Miiri Parish', 'Karatina Deanery'),
('Giakaibei Parish', 'Karatina Deanery'),
('Gikumbo Parish', 'Karatina Deanery'),
('Gathugu Parish', 'Karatina Deanery'),
('Ngandu Parish', 'Karatina Deanery'),
('Kabiru-ini Parish', 'Karatina Deanery'),
('Kahira-ini Parish', 'Karatina Deanery'),
('Tetu Parish', 'Tetu Deanery'),
('Wamagana Parish', 'Tetu Deanery'),
('Kigogo-ini Parish', 'Tetu Deanery'),
('Itheguri Parish', 'Tetu Deanery'),
('Gititu Parish', 'Tetu Deanery'),
('Kangaita Parish', 'Tetu Deanery'),
('Giakanja Parish', 'Tetu Deanery'),
('Karangia Parish', 'Tetu Deanery'),
('Mweiga Parish', 'Gatarakwa Deanery'),
('Endarasha Parish', 'Gatarakwa Deanery'),
('Gatarakwa Parish', 'Gatarakwa Deanery'),
('Karemeno Parish', 'Gatarakwa Deanery'),
('Mugunda Parish', 'Gatarakwa Deanery'),
('Sirima Parish', 'Gatarakwa Deanery'),
('Winyumiririe Parish', 'Gatarakwa Deanery'),
('Kamariki Parish', 'Gatarakwa Deanery');