-- Generated by the database client.
CREATE TABLE users(
    id SERIAL NOT NULL,
    role varchar(20),
    email varchar(100),
    password_hash text,
    father varchar(100),
    mother varchar(100),
    tribe varchar(50),
    clan varchar(50),
    birth_place varchar(100),
    birth_date date,
    subcounty varchar(100),
    residence varchar(150),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    parish_id integer,
    verified boolean DEFAULT false,
    phone_number varchar(20),
    first_name varchar(100),
    last_name varchar(100),
    middle_name varchar(100),
    registration_number varchar(50),
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);
CREATE UNIQUE INDEX registration_number_unique ON public.users USING btree (registration_number);


-- Generated by the database client.
CREATE TABLE parishes(
    parish_id SERIAL NOT NULL,
    parish_name varchar(100) NOT NULL,
    deanery varchar(100) NOT NULL,
    PRIMARY KEY(parish_id)
);


-- Generated by the database client.
CREATE TABLE baptism(
    baptism_id SERIAL NOT NULL,
    user_id integer,
    parish varchar(100),
    baptism_date date,
    minister varchar(100),
    sponsor varchar(100),
    baptism_number varchar(50),
    PRIMARY KEY(baptism_id),
    CONSTRAINT baptism_user_id_fkey FOREIGN key(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX baptism_baptism_number_key ON public.baptism USING btree (baptism_number);


-- Generated by the database client.
CREATE TABLE confirmation(
    confirmation_id SERIAL NOT NULL,
    user_id integer,
    confirmation_place varchar(100),
    confirmation_date date,
    confirmation_no varchar(50),
    minister varchar(100),
    PRIMARY KEY(confirmation_id),
    CONSTRAINT confirmation_user_id_fkey FOREIGN key(user_id) REFERENCES users(id) ON DELETE CASCADE
);



-- Generated by the database client.
CREATE TABLE eucharist(
    eucharist_id SERIAL NOT NULL,
    user_id integer,
    eucharist_place varchar(100),
    eucharist_date date,
    PRIMARY KEY(eucharist_id),
    CONSTRAINT eucharist_user_id_fkey FOREIGN key(user_id) REFERENCES users(id) ON DELETE CASCADE
);



-- Generated by the database client.
CREATE TABLE marriages(
    marriage_id SERIAL NOT NULL,
    user_id integer NOT NULL,
    certificate_number varchar(50),
    submission_location varchar(100),
    submission_sub_county varchar(100),
    submission_county varchar(100),
    marriage_date date,
    marriage_entry_number varchar(50),
    special_license_number varchar(50),
    conducted_by varchar(100),
    private_parties_count integer,
    private_parties_names text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    registrar_certification_number varchar(50),
    PRIMARY KEY(marriage_id),
    CONSTRAINT marriages_user_id_fkey FOREIGN key(user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user FOREIGN key(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX marriages_certificate_number_key ON public.marriages USING btree (certificate_number);



-- Generated by the database client.
CREATE TABLE marriage_parties(
    party_id SERIAL NOT NULL,
    marriage_id integer NOT NULL,
    party_type varchar(20),
    full_name varchar(100),
    age integer,
    marital_status varchar(50),
    residence_address text,
    residence_county varchar(100),
    residence_sub_county varchar(100),
    occupation varchar(100),
    father_name varchar(100),
    father_occupation varchar(100),
    father_residence text,
    mother_name varchar(100),
    mother_occupation varchar(100),
    mother_residence text,
    PRIMARY KEY(party_id),
    CONSTRAINT marriage_parties_marriage_id_fkey FOREIGN key(marriage_id) REFERENCES marriages(marriage_id) ON DELETE CASCADE,
    CONSTRAINT marriage_parties_party_type_check CHECK ((party_type)::text = ANY ((ARRAY['bride'::character varying, 'groom'::character varying])::text[]))
);



-- Generated by the database client.
CREATE TABLE marriage_documents(
    document_id SERIAL NOT NULL,
    marriage_id integer NOT NULL,
    document_type varchar(50),
    file_name varchar(255),
    file_path text,
    file_size bigint,
    uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(document_id),
    CONSTRAINT marriage_documents_marriage_id_fkey FOREIGN key(marriage_id) REFERENCES marriages(marriage_id) ON DELETE CASCADE
);



INSERT INTO parishes (parish_name, deanery) VALUES
('Cathedral Parish', 'Nyeri Municipality Deanery'),
('St. Jude Parish', 'Nyeri Municipality Deanery'),
('King''ong''o Parish', 'Nyeri Municipality Deanery'),
('Mwenji Parish', 'Nyeri Municipality Deanery'),
('Kiamuiru Parish', 'Nyeri Municipality Deanery'),
('Mathari Institutions Chaplaincy', 'Nyeri Municipality Deanery'),
('St. Charles Lwanga Parish', 'Nyeri Municipality Deanery'),
('Mukurwe-ini Parish', 'Mukurwe-ini Deanery'),
('Kaheti Parish', 'Mukurwe-ini Deanery'),
('Kimondo Parish', 'Mukurwe-ini Deanery'),
('Gikondi Parish', 'Mukurwe-ini Deanery'),
('Othaya Parish', 'Othaya Deanery'),
('Kariko Parish', 'Othaya Deanery'),
('Birithia Parish', 'Othaya Deanery'),
('Karima Parish', 'Othaya Deanery'),
('Kagicha Parish', 'Othaya Deanery'),
('Karuthi Parish', 'Othaya Deanery'),
('Kigumo Parish', 'Othaya Deanery'),
('Nanyuki Parish', 'Nanyuki Deanery'),
('Dol Dol Parish', 'Nanyuki Deanery'),
('Matanya Parish', 'Nanyuki Deanery'),
('St. Teresa Parish', 'Nanyuki Deanery'),
('Kalalu Parish', 'Nanyuki Deanery'),
('Narumoru Town Parish', 'Narumoru Deanery'),
('Irigithathi Parish', 'Narumoru Deanery'),
('Thegu Parish', 'Narumoru Deanery'),
('Arch-angel Michael Chaka Parish', 'Narumoru Deanery'),
('Munyu Parish', 'Narumoru Deanery'),
('Karatina Parish', 'Karatina Deanery'),
('Miiri Parish', 'Karatina Deanery'),
('Giakaibei Parish', 'Karatina Deanery'),
('Gikumbo Parish', 'Karatina Deanery'),
('Gathugu Parish', 'Karatina Deanery'),
('Ngandu Parish', 'Karatina Deanery'),
('Kabiru-ini Parish', 'Karatina Deanery'),
('Kahira-ini Parish', 'Karatina Deanery'),
('Tetu Parish', 'Tetu Deanery'),
('Wamagana Parish', 'Tetu Deanery'),
('Kigogo-ini Parish', 'Tetu Deanery'),
('Itheguri Parish', 'Tetu Deanery'),
('Gititu Parish', 'Tetu Deanery'),
('Kangaita Parish', 'Tetu Deanery'),
('Giakanja Parish', 'Tetu Deanery'),
('Karangia Parish', 'Tetu Deanery'),
('Mweiga Parish', 'Gatarakwa Deanery'),
('Endarasha Parish', 'Gatarakwa Deanery'),
('Gatarakwa Parish', 'Gatarakwa Deanery'),
('Karemeno Parish', 'Gatarakwa Deanery'),
('Mugunda Parish', 'Gatarakwa Deanery'),
('Sirima Parish', 'Gatarakwa Deanery'),
('Winyumiririe Parish', 'Gatarakwa Deanery'),
('Kamariki Parish', 'Gatarakwa Deanery');
